import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import { IoImageOutline, IoSettingsOutline } from "react-icons/io5";
import { FaMeta } from "react-icons/fa6";
import { SiShopify } from "react-icons/si";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <aside className="w-20 h-screen bg-black flex flex-col items-center fixed top-0 left-0">
          <div className="flex flex-col items-center justify-center cursor-pointer">
            <img
              src="/logo.png"
              alt="Logo"
              className="w-10 h-10 mx-auto my-8"
            />
          </div>
          <ul className="text-gray-400 text-4xl flex flex-col items-center justify-center gap-8 my-6">
            <li className="cursor-pointer">
              <IoImageOutline />
            </li>
            <li className="cursor-pointer">
              <FaMeta />
            </li>
            <li className="cursor-pointer">
              <SiShopify />
            </li>
          </ul>
          <div className="text-gray-400 text-3xl absolute bottom-4 cursor-pointer">
            <IoSettingsOutline />
          </div>
        </aside>
        {children}
      </body>
    </html>
  );
}
